name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # BASIC
          user: sumitkr-2
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata

          # LOOK
          config_display: large
          config_output: svg
          config_padding: 16
          config_border_radius: 12

          # LANGUAGES
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: percentage

          # GRAPHS
          plugin_habits: yes
          plugin_habits_charts: yes

          # 3D CALENDAR
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # ACTIVITY
          plugin_activity: yes

          # STREAK
          plugin_streak: yes

          # PEOPLE
          plugin_people: yes
          plugin_people_types: followers, following

          # REPOS
          plugin_repositories: yes
          plugin_repositories_featured: my_website-portfolio, Cartoon_memory

          # ICONS
          plugin_topics: yes

          metadata: yes
